site_name: Faster Pytorch
site_url: https://finger-bone.github.io/fater-pytorch/
site_description: An introduction to accelerating PyTorch tools

theme:
  name: lux
  font:
    text: Inter
    code: Fira Code

docs_dir: notes

nav:
- Wandb: 01Wandb/01
- Lightning: 02Lightning/02
- Deepspeed: 03Deepspeed/03
- Fairscale: 04Fairscale/04
- Fabric and Accelerate: 05FabricAndAccelerate/05

extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
  mdx_math:
    enable_dollar_delimiter: true
