wandb_version: 1

lr:
  desc: null
  value: 0.0001
epoch:
  desc: null
  value: 3
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721465209
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 15
      - 16
      - 23
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 5
      13: darwin-arm64
