wandb_version: 1

lr:
  desc: null
  value: 0.0001
epoch:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 128
weight_decay:
  desc: null
  value: 1.0e-05
_wandb:
  desc: null
  value:
    python_version: 3.12.4
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1721470129
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 7
      - 13
      - 15
      - 16
      - 23
      - 62
      - 63
      4: 3.12.4
      5: 0.17.5
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
    m:
    - 1: loss
      6:
      - 3
      7:
      - 1
